const BUCKET = "vendor-images";

// Transitional shim for legacy assets paths still generated by older migrations.
const LEGACY_PREFIX = "/assets/customer/";

/**
 * Converts a bucket-relative vendor-image path into a public URL.
 * Returns null for empty input; passes absolute URLs through unchanged.
 */
export function vendorImageUrl(path: string | null | undefined): string | null {
  if (!path) return null;
  if (path.startsWith("http://") || path.startsWith("https://")) return path;

  let objectPath = path.startsWith(LEGACY_PREFIX) ? path.slice(LEGACY_PREFIX.length) : path;
  objectPath = objectPath.replace(/^\/+/, "");

  const base = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
  return `${base}/storage/v1/object/public/${BUCKET}/${objectPath}`;
}
