-- Populate one curated, locally-served cover image for every approved vendor.
-- Sources and attribution are recorded in public/assets/customer/vendor-images/PHOTO-CREDITS.md.
begin;

update public.vendors as v
set cover_url = case v.slug
  when 'abdul-antiques' then '/assets/customer/vendor-images/abdul-antiques.jpg'
  when 'agensi-ekspres-yew-ngee' then '/assets/customer/vendor-images/agensi-ekspres-yew-ngee.jpg'
  when 'alibaba' then '/assets/customer/vendor-images/alibaba.jpg'
  when 'atlas-travel-services' then '/assets/customer/vendor-images/atlas-travel-services.jpg'
  when 'avante-holidays' then '/assets/customer/vendor-images/avante-holidays.jpg'
  when 'baba-nyonya-heritage-trust' then '/assets/customer/vendor-images/baba-nyonya-heritage-trust.jpg'
  when 'baba-house-hotel' then '/assets/customer/vendor-images/baba-house-hotel.jpg'
  when 'baboon-house' then '/assets/customer/vendor-images/baboon-house.jpg'
  when 'bagus-holiday' then '/assets/customer/vendor-images/bagus-holiday.jpg'
  when 'balas-chalet' then '/assets/customer/vendor-images/balas-chalet.jpg'
  when 'barracks-cafe' then '/assets/customer/vendor-images/barracks-cafe.jpg'
  when 'best-western-shah-alam' then '/assets/customer/vendor-images/best-western-shah-alam.jpg'
  when 'border-bazzar-padang-besar' then '/assets/customer/vendor-images/border-bazzar-padang-besar.jpg'
  when 'cs-travel-and-tours' then '/assets/customer/vendor-images/cs-travel-and-tours.jpg'
  when 'cameron-highlands-forestry' then '/assets/customer/vendor-images/cameron-highlands-forestry.jpg'
  when 'cameron-valley-tea-shop' then '/assets/customer/vendor-images/cameron-valley-tea-shop.jpg'
  when 'capitol-satay-celup' then '/assets/customer/vendor-images/capitol-satay-celup.jpg'
  when 'casa-del-mar' then '/assets/customer/vendor-images/casa-del-mar.jpg'
  when 'chaiwalla-and-co' then '/assets/customer/vendor-images/chaiwalla-and-co.jpg'
  when 'cheong-fatt-tze-blue-mansion' then '/assets/customer/penang/cheong-fatt-tze-mansion.webp'
  when 'chia-bee-bah-kut-teh' then '/assets/customer/vendor-images/chia-bee-bah-kut-teh.jpg'
  when 'chong-kok-kopitiam' then '/assets/customer/vendor-images/chong-kok-kopitiam.jpg'
  when 'courtyard-heeren' then '/assets/customer/vendor-images/courtyard-heeren.jpg'
  when 'desa-murni-batik' then '/assets/customer/vendor-images/desa-murni-batik.jpg'
  when 'dj-citi-point-hotel' then '/assets/customer/vendor-images/dj-citi-point-hotel.jpg'
  when 'dragon-art-valley' then '/assets/customer/vendor-images/dragon-art-valley.jpg'
  when 'eastern-oriental-hotel' then '/assets/customer/penang/eastern-oriental-hotel.webp'
  when 'entopia-penang-butterfly-farm' then '/assets/customer/vendor-images/entopia-penang-butterfly-farm.jpg'
  when 'escape-penang' then '/assets/customer/vendor-images/escape-penang.jpg'
  when 'excelsior-hotel' then '/assets/customer/vendor-images/excelsior-hotel.jpg'
  when 'famosa-chicken-rice-ball' then '/assets/customer/vendor-images/famosa-chicken-rice-ball.jpg'
  when 'flywind-holidays' then '/assets/customer/vendor-images/flywind-holidays.jpg'
  when 'foo-phing-dim-sum' then '/assets/customer/vendor-images/foo-phing-dim-sum.jpg'
  when 'furama-hotel' then '/assets/customer/vendor-images/furama-hotel.jpg'
  when 'geographer-cafe' then '/assets/customer/vendor-images/geographer-cafe.jpg'
  when 'gerakbudaya-bookshop-penang' then '/assets/customer/vendor-images/gerakbudaya-bookshop-penang.jpg'
  when 'ghee-hiang' then '/assets/customer/vendor-images/ghee-hiang.jpg'
  when 'go-aquatic-diving' then '/assets/customer/vendor-images/go-aquatic-diving.jpg'
  when 'good-times-travel' then '/assets/customer/vendor-images/good-times-travel.jpg'
  when 'hameed-nasi-kandar' then '/assets/customer/vendor-images/hameed-nasi-kandar.jpg'
  when 'hameediyah-restaurant' then '/assets/customer/vendor-images/hameediyah-restaurant.jpg'
  when 'heritage-hotel-cameron-highlands' then '/assets/customer/vendor-images/heritage-hotel-cameron-highlands.jpg'
  when 'hiap-joo-bakery' then '/assets/customer/vendor-images/hiap-joo-bakery.jpg'
  when 'highlands-skyway-operations' then '/assets/customer/vendor-images/highlands-skyway-operations.jpg'
  when 'hill-top-travel-tour' then '/assets/customer/vendor-images/hill-top-travel-tour.jpg'
  when 'hilton-kuching' then '/assets/customer/vendor-images/hilton-kuching.jpg'
  when 'him-heang' then '/assets/customer/vendor-images/him-heang.jpg'
  when 'histana-hotel' then '/assets/customer/vendor-images/histana-hotel.jpg'
  when 'hong-hin' then '/assets/customer/vendor-images/hong-hin.jpg'
  when 'hotel-ciq' then '/assets/customer/vendor-images/hotel-ciq.jpg'
  when 'hotel-classic-muar' then '/assets/customer/vendor-images/hotel-classic-muar.jpg'
  when 'hotel-langkasuka' then '/assets/customer/vendor-images/hotel-langkasuka.jpg'
  when 'hotel-puri' then '/assets/customer/vendor-images/hotel-puri.jpg'
  when 'hotel-sri-garden' then '/assets/customer/vendor-images/hotel-sri-garden.jpg'
  when 'hotel-sri-tanjung' then '/assets/customer/vendor-images/hotel-sri-tanjung.jpg'
  when 'hotel-sri-terengganu' then '/assets/customer/vendor-images/hotel-sri-terengganu.jpg'
  when 'ibis-styles-kota-bharu' then '/assets/customer/vendor-images/ibis-styles-kota-bharu.jpg'
  when 'island-connection-travel-tours' then '/assets/customer/vendor-images/island-connection-travel-tours.jpg'
  when 'istana-jahar-vendor' then '/assets/customer/vendor-images/istana-jahar-vendor.jpg'
  when 'james-brooke-cafe' then '/assets/customer/vendor-images/james-brooke-cafe.jpg'
  when 'jom-kembara-travel-tour' then '/assets/customer/vendor-images/jom-kembara-travel-tour.jpg'
  when 'jonker-88-heritage' then '/assets/customer/vendor-images/jonker-88-heritage.jpg'
  when 'kakilang-kopitiam' then '/assets/customer/vendor-images/kakilang-kopitiam.jpg'
  when 'kapit-adventure-tours' then '/assets/customer/vendor-images/kapit-adventure-tours.jpg'
  when 'kee-mei-siew-pow' then '/assets/customer/vendor-images/kee-mei-siew-pow.jpg'
  when 'kek-lok-si-temple-vendor' then '/assets/customer/penang/kek-lok-si-temple.webp'
  when 'kelantan-silk-store' then '/assets/customer/vendor-images/kelantan-silk-store.jpg'
  when 'kemaman-kopitiam' then '/assets/customer/vendor-images/kemaman-kopitiam.jpg'
  when 'klang-valley-travel-tours' then '/assets/customer/vendor-images/klang-valley-travel-tours.jpg'
  when 'kobe-sizzlers' then '/assets/customer/vendor-images/kobe-sizzlers.jpg'
  when 'kooya-handicraft' then '/assets/customer/vendor-images/kooya-handicraft.jpg'
  when 'kuala-selangor-firefly-park-resort' then '/assets/customer/vendor-images/kuala-selangor-firefly-park-resort.jpg'
  when 'kwan-kee' then '/assets/customer/vendor-images/kwan-kee.jpg'
  when 'lam-fong-biscuit-house' then '/assets/customer/vendor-images/lam-fong-biscuit-house.jpg'
  when 'langkawi-cable-car' then '/assets/customer/vendor-images/langkawi-cable-car.jpg'
  when 'langkawi-yummy-yummy-seafood' then '/assets/customer/vendor-images/langkawi-yummy-yummy-seafood.jpg'
  when 'legoland-hotel-malaysia' then '/assets/customer/vendor-images/legoland-hotel-malaysia.jpg'
  when 'legoland-malaysia-resort' then '/assets/customer/vendor-images/legoland-malaysia-resort.jpg'
  when 'khoo-kongsi-trust' then '/assets/customer/penang/khoo-kongsi.webp'
  when 'lexis-hibiscus-port-dickson' then '/assets/customer/vendor-images/lexis-hibiscus-port-dickson.jpg'
  when 'lingams-curry-house' then '/assets/customer/vendor-images/lingams-curry-house.jpg'
  when 'love-island-tours' then '/assets/customer/vendor-images/love-island-tours.jpg'
  when 'loyal-maxim-duty-free' then '/assets/customer/vendor-images/loyal-maxim-duty-free.jpg'
  when 'madam-bees-kitchen' then '/assets/customer/vendor-images/madam-bees-kitchen.jpg'
  when 'maheran-laksa' then '/assets/customer/vendor-images/maheran-laksa.jpg'
  when 'mans-cafe' then '/assets/customer/vendor-images/mans-cafe.jpg'
  when 'mari-mari-cultural-village' then '/assets/customer/vendor-images/mari-mari-cultural-village.jpg'
  when 'mariammah-curry-house' then '/assets/customer/vendor-images/mariammah-curry-house.jpg'
  when 'mariners-cafe' then '/assets/customer/vendor-images/mariners-cafe.jpg'
  when 'mei-fong-curry-noodles' then '/assets/customer/vendor-images/mei-fong-curry-noodles.jpg'
  when 'melaka-museums-corporation' then '/assets/customer/vendor-images/melaka-museums-corporation.jpg'
  when 'melaka-river-cruise-vendor' then '/assets/customer/vendor-images/melaka-river-cruise-vendor.jpg'
  when 'menara-alor-setar-management' then '/assets/customer/vendor-images/menara-alor-setar-management.jpg'
  when 'menara-taming-sari-vendor' then '/assets/customer/vendor-images/menara-taming-sari-vendor.jpg'
  when 'mersing-seafood-restaurant' then '/assets/customer/vendor-images/mersing-seafood-restaurant.jpg'
  when 'mossy-cameron' then '/assets/customer/vendor-images/mossy-cameron.jpg'
  when 'muzium-diraja-istana-lama-seri-menanti' then '/assets/customer/vendor-images/muzium-diraja-istana-lama-seri-menanti.jpg'
  when 'nam-heong-old-town-white-coffee' then '/assets/customer/vendor-images/nam-heong-old-town-white-coffee.jpg'
  when 'nan-feng-restoran' then '/assets/customer/vendor-images/nan-feng-restoran.jpg'
  when 'nasi-dagang-vintage' then '/assets/customer/vendor-images/nasi-dagang-vintage.jpg'
  when 'nasi-kandar-line-clear' then '/assets/customer/vendor-images/nasi-kandar-line-clear.jpg'
  when 'nz-world-travels' then '/assets/customer/vendor-images/nz-world-travels.jpg'
  when 'pak-putra-tandoori' then '/assets/customer/vendor-images/pak-putra-tandoori.jpg'
  when 'palm-seremban-hotel' then '/assets/customer/vendor-images/palm-seremban-hotel.jpg'
  when 'paradise-craft' then '/assets/customer/vendor-images/paradise-craft.jpg'
  when 'pasir-belanda' then '/assets/customer/vendor-images/pasir-belanda.jpg'
  when 'pelangi-beach-resort-spa' then '/assets/customer/vendor-images/pelangi-beach-resort-spa.jpg'
  when 'penang-heritage-trust' then '/assets/customer/vendor-images/penang-heritage-trust.jpg'
  when 'penang-hill-corporation' then '/assets/customer/penang/penang-hill.webp'
  when 'penang-national-park' then '/assets/customer/vendor-images/penang-national-park.jpg'
  when 'penang-road-famous-teochew-chendul' then '/assets/customer/vendor-images/penang-road-famous-teochew-chendul.jpg'
  when 'pinang-peranakan-mansion-vendor' then '/assets/customer/penang/pinang-peranakan-mansion.webp'
  when 'pine-beach-hotel' then '/assets/customer/vendor-images/pine-beach-hotel.jpg'
  when 'planters-hotel' then '/assets/customer/vendor-images/planters-hotel.jpg'
  when 'pullman-kuching' then '/assets/customer/vendor-images/pullman-kuching.jpg'
  when 'putra-regency-hotel' then '/assets/customer/vendor-images/putra-regency-hotel.jpg'
  when 'redang-pelangi-resort' then '/assets/customer/vendor-images/redang-pelangi-resort.jpg'
  when 'restaurant-ee-lo' then '/assets/customer/vendor-images/restaurant-ee-lo.jpg'
  when 'restoran-ah-piaw' then '/assets/customer/vendor-images/restoran-ah-piaw.jpg'
  when 'restoran-cendol-sarah' then '/assets/customer/vendor-images/restoran-cendol-sarah.jpg'
  when 'restoran-ferm-nyonya' then '/assets/customer/vendor-images/restoran-ferm-nyonya.jpg'
  when 'restoran-hoi-yin' then '/assets/customer/vendor-images/restoran-hoi-yin.jpg'
  when 'restoran-hoong-kee' then '/assets/customer/vendor-images/restoran-hoong-kee.jpg'
  when 'restoran-nasi-kandar-yasmeen' then '/assets/customer/vendor-images/restoran-nasi-kandar-yasmeen.jpg'
  when 'seng-huat-bak-kut-teh' then '/assets/customer/vendor-images/seng-huat-bak-kut-teh.jpg'
  when 'restoran-tauge-ayam-lou-wong' then '/assets/customer/vendor-images/restoran-tauge-ayam-lou-wong.jpg'
  when 'restoran-wah-san' then '/assets/customer/vendor-images/restoran-wah-san.jpg'
  when 'salt-x-paper' then '/assets/customer/vendor-images/salt-x-paper.jpg'
  when 'sam-kee-kopitiam' then '/assets/customer/vendor-images/sam-kee-kopitiam.jpg'
  when 'samila-hotel' then '/assets/customer/vendor-images/samila-hotel.jpg'
  when 'sandy-beach-resort' then '/assets/customer/vendor-images/sandy-beach-resort.jpg'
  when 'seremban-travel-tours' then '/assets/customer/vendor-images/seremban-travel-tours.jpg'
  when 'shangrila-tanjung-aru' then '/assets/customer/vendor-images/shangrila-tanjung-aru.jpg'
  when 'shangri-la-rasa-sayang' then '/assets/customer/vendor-images/shangri-la-rasa-sayang.jpg'
  when 'sin-yoon-loong' then '/assets/customer/vendor-images/sin-yoon-loong.jpg'
  when 'sri-daya-travels' then '/assets/customer/vendor-images/sri-daya-travels.jpg'
  when 'sticky-rice-travel' then '/assets/customer/vendor-images/sticky-rice-travel.jpg'
  when 'sunway-lost-world-of-tambun' then '/assets/customer/vendor-images/sunway-lost-world-of-tambun.jpg'
  when 'taman-negara-park-authority' then '/assets/customer/vendor-images/taman-negara-park-authority.jpg'
  when 'taman-tamadun-islam' then '/assets/customer/vendor-images/taman-tamadun-islam.jpg'
  when 'taman-ular-dan-reptilia-sungai-batu-pahat' then '/assets/customer/vendor-images/taman-ular-dan-reptilia-sungai-batu-pahat.jpg'
  when 'tanoti-weavers-workshop' then '/assets/customer/vendor-images/tanoti-weavers-workshop.jpg'
  when 'tc-curry-house' then '/assets/customer/vendor-images/tc-curry-house.jpg'
  when 'teraju-travel-tours' then '/assets/customer/vendor-images/teraju-travel-tours.jpg'
  when 'the-clay-house' then '/assets/customer/vendor-images/the-clay-house.jpg'
  when 'the-cliff-restaurant' then '/assets/customer/vendor-images/the-cliff-restaurant.jpg'
  when 'the-habitat-penang-hill' then '/assets/customer/vendor-images/the-habitat-penang-hill.jpg'
  when 'the-jesselton-hotel' then '/assets/customer/vendor-images/the-jesselton-hotel.jpg'
  when 'the-limetree-hotel' then '/assets/customer/vendor-images/the-limetree-hotel.jpg'
  when 'the-majestic-station-hotel' then '/assets/customer/vendor-images/the-majestic-station-hotel.jpg'
  when 'the-pacific-sutera' then '/assets/customer/vendor-images/the-pacific-sutera.jpg'
  when 'the-zon-duty-free' then '/assets/customer/vendor-images/the-zon-duty-free.jpg'
  when 'thistle-johor-bahru' then '/assets/customer/vendor-images/thistle-johor-bahru.jpg'
  when 'thistle-port-dickson' then '/assets/customer/vendor-images/thistle-port-dickson.jpg'
  when 'timotel-hotel' then '/assets/customer/vendor-images/timotel-hotel.jpg'
  when 'tioman-marine-park-vendor' then '/assets/customer/vendor-images/tioman-marine-park-vendor.jpg'
  when 'toh-soon-cafe' then '/assets/customer/vendor-images/toh-soon-cafe.jpg'
  when 'tropical-spice-garden' then '/assets/customer/vendor-images/tropical-spice-garden.jpg'
  when 'tune-hotel-kota-bharu' then '/assets/customer/vendor-images/tune-hotel-kota-bharu.jpg'
  when 'twenty-trees-boutique-hotel' then '/assets/customer/vendor-images/twenty-trees-boutique-hotel.jpg'
  when 'uncle-chow-kopitiam' then '/assets/customer/vendor-images/uncle-chow-kopitiam.jpg'
  when 'underwater-world-langkawi' then '/assets/customer/vendor-images/underwater-world-langkawi.jpg'
  when 'upside-down-house-kuching' then '/assets/customer/vendor-images/upside-down-house-kuching.jpg'
  when 'welcome-seafood-restaurant' then '/assets/customer/vendor-images/welcome-seafood-restaurant.jpg'
  when 'yasmin-syrian' then '/assets/customer/vendor-images/yasmin-syrian.jpg'
  when 'yati-ayam-percik' then '/assets/customer/vendor-images/yati-ayam-percik.jpg'
  when 'yee-kee-beef-noodles' then '/assets/customer/vendor-images/yee-kee-beef-noodles.jpg'
  when 'yoyo-holiday' then '/assets/customer/vendor-images/yoyo-holiday.jpg'
  when 'zarkasyi-travel' then '/assets/customer/vendor-images/zarkasyi-travel.jpg'
  when 'zhun-san-yen-vegetarian' then '/assets/customer/vendor-images/zhun-san-yen-vegetarian.jpg'
  else v.cover_url
end
where v.status = 'approved';

do $$
declare
  approved_count integer;
  covered_count integer;
  distinct_cover_count integer;
begin
  select count(*) into approved_count from public.vendors where status = 'approved';
  select count(*) into covered_count from public.vendors where status = 'approved' and cover_url is not null and btrim(cover_url) <> '';
  select count(distinct cover_url) into distinct_cover_count from public.vendors where status = 'approved' and cover_url is not null and btrim(cover_url) <> '';
  if covered_count <> approved_count then
    raise exception 'approved vendor image coverage incomplete: % of %', covered_count, approved_count;
  end if;
  if distinct_cover_count <> approved_count then
    raise exception 'approved vendor image paths are not unique: % distinct of %', distinct_cover_count, approved_count;
  end if;
end $$;

commit;
