"use client";

import { useEffect, useState } from "react";
import { NotificationBell } from "@/components/shared/notification-bell";

const filters = [['all', 'All'], ['unread', 'Unread'], ['wallet', 'Wallet'], ['bookings_purchases', 'Bookings & Purchases'], ['recommendations_affiliate', 'Recommendations & Affiliate'], ['support', 'Support'], ['account_security', 'Account & Security']] as const;
type Item = { id: string; title: string; body: string; link: string | null; readAt: string | null; createdAt: string };

export default function NotificationsPage() {
  const [filter, setFilter] = useState('all'); const [items, setItems] = useState<Item[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1);
  useEffect(() => { (async () => { const params = new URLSearchParams({ page: String(page), pageSize: '15' }); if (filter === 'unread') params.set('read', 'unread'); else if (filter !== 'all') params.set('category', filter); const response = await fetch(`/api/notifications?${params}`); const body = await response.json() as { data?: { items: Item[]; totalPages: number } }; if (response.ok && body.data) { setItems(body.data.items); setTotalPages(body.data.totalPages); } })(); }, [filter, page]);
  return <div className="mx-auto max-w-3xl px-4 py-8"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Account</p><h1 className="text-2xl font-bold">Notifications</h1></div><NotificationBell /></div><div className="mb-5 flex flex-wrap gap-2">{filters.map(([value, label]) => <button key={value} type="button" onClick={() => { setFilter(value); setPage(1); }} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${filter === value ? 'border-primary bg-primary text-white' : 'border-border text-muted-foreground'}`}>{label}</button>)}</div><div className="rounded-2xl border border-border bg-card">{items.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">No notifications found.</p> : items.map((item) => <div key={item.id} className={`border-b border-border px-5 py-4 last:border-0 ${item.readAt ? '' : 'bg-primary/5'}`}><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.body}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString('en-MY')}</p></div>)}</div><div className="mt-4 flex items-center justify-between text-sm"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border border-border px-3 py-2 disabled:opacity-50">Previous</button><span>Page {page} of {totalPages}</span><button type="button" disabled={page >= totalPages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border border-border px-3 py-2 disabled:opacity-50">Next</button></div></div>;
}
